name: Python package
on:
  push:
    tags:
      - "v*.*.*"
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install system dependencies
        run: sudo apt update && sudo apt install -y liblz4-dev

      - uses: actions/checkout@v3
      - name: Build and publish to pypi
        uses: JRubics/poetry-publish@v2.1
        with:
          python_version: "3.10"
          poetry_version: "==2.2.0"
          pypi_token: ${{ secrets.PYPI_TOKEN }}
